# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.0.9
_src_path: gh:FallingColors/hexdummy
author: TechTastic
capitalize_platforms: false
classname: Hexcasted
default_branch: main
description: 'A Hexcasting x Create: Big Cannons Addon'
display_name: Hexcasted
github_repo: hex-casted
hexcasting_version: 0.11.1-7-pre-646
homepage_url: https://techtastic.github.io/hex-casted
initial_mod_version: 0.0.1
java_version: 17
license: MIT
mappings_name: Mojmap
modid: hexcasted
package: io.github.techtastic.hexcasted
sources_url: https://github.com/TechTastic/hex-casted
