author: TechTastic
book_id: "hexcasted:hexcastedbook"
default_branch: main
github_repo: hex-casted
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: HexcastedModPlugin
hexdoc_plugin_classname: HexcastedPlugin
java_lang:
  ext: java
  src: java
java_package: io/github/techtastic/hexcasted
mod_display_name: Hexcasted
modid: hexcasted
multiloader: true
pages_url: https://techtastic.github.io/hex-casted
pattern_regex:
  regex: '(?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?'
  per_world_value: registerPerWorld
pattern_registry: registry/HexcastedPatternRegistry.java
